export default function HomePage() {
  return (
    <main className='min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100'>
      <div className='container mx-auto px-4 py-16'>
        <div className='text-center'>
          <h1 className='text-4xl font-bold text-gray-900 mb-4'>
            Welcome to SolfaMe
          </h1>
          <p className='text-xl text-gray-600 mb-8'>
            AI-powered music transcription for choir education
          </p>
          <div className='bg-white rounded-lg shadow-lg p-8 max-w-md mx-auto'>
            <h2 className='text-2xl font-semibold text-gray-800 mb-4'>
              Transform Music Into Choir Parts
            </h2>
            <p className='text-gray-600 mb-6'>
              Upload a YouTube link and get SATB vocal parts with solfa notation
              automatically generated by AI.
            </p>
            <div className='space-y-4'>
              <input
                type='url'
                placeholder='Paste YouTube URL here...'
                className='w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500'
                disabled
              />
              <button
                className='w-full bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-700 transition-colors disabled:opacity-50'
                disabled
              >
                Process Music (Coming Soon)
              </button>
            </div>
          </div>
        </div>
      </div>
    </main>
  );
}
